### PR TITLE
Bhberson social short codes

### PR DESCRIPTION
**Pull request by ifraixedes**
This PR overtake #1 to provide examples, provide more doc and fix issues that.

@bhberson I would like to ask to discuss with you a few things:
1. I couldn't make "Pinterestes pinit" shortcode works using [positional parameters](https://gohugo.io/extras/shortcodes/). The problem is that the option to use positional parameters call functions which are available in [Node or Page](https://gohugo.io/templates/variables/) so it crash to call them.
2. Due the issue mentioned in (1) I would prefer not to have two options to use the shortcode, the implementation is simple and it's less confusing how to use them. I would follow the suggestion mentioned in [Creating your own shortcodes](https://gohugo.io/extras/shortcodes/#creating-your-own-shortcodes:10ef41a6c37b90d6a6452868d5ba00ba).
   In this case it seems that the "facebook share" is fine to use a positional parameter and the rest are fine using named parameters which I like the checks that you have used to set or not the property.

What do you think?

### CODE REVIEW

**Comment by mynamebrody** [comment]
Ahh I see what you are saying about the "Pinit" shortcode. I give a 👍on everything else you mentioned and have changed here. Do you have any suggestions for the "pinit" one to make it functional? Otherwise I can take a look at it later on in my day.

**Comment by ifraixedes** [comment]
@bhberson Ah sorry, I could have added it using the named parameters after realise that it didn't work with the positional parameters because it calls `.Permalink` and inside of the shortcode `.` is nothing or maybe something but it isn't a Node nor Page.

Because you are happy with having the shortcodes only with named parameters then I think that "pinit" will work.

I'm going to test the "pinit" now

**Comment by mynamebrody** [comment]
Will look at adding others soon: https://developers.facebook.com/docs/plugins Such as embed a post, like button, etc. I'm sure this social media list could go on forever

**Comment by ifraixedes** [comment]
@bhberson actually the "pinit" cannot work as it's dude that the named parameters options it uses several Page variables as `.Site.BaseURL`.
The error that I get now is

```
ERR: template: theme/shortcodes/pinterest-pinit.html:1:280: executing "theme/shortcodes/pinterest-pinit.html" at <.Site.BaseURL>: Site is not a field of struct type *hugolib.ShortcodeWithPage
```

The change that we have to do is get rid of any variable reference by `.` and only use the named parameters values and default constant values for those options that can be constant.

If you want to do this changes go ahead, otherwise I will do tomorrow as here is time to go to bed :smile: 

If you want to add more, they are welcome, but I think that we can add them in another PR.
I'm going to give you write access to the repository, but please keep working through branches and sending PR to be able to review each other.

**Comment by ifraixedes** [comment]
@bhberson I'm working on them, I am almost done, I only to do two shortcodes more to finish, but I will do later, before going to bed, as know I have to go.

I've also added the parameters that they accept in the `social-sharing.md` file as a documentation. When I'll wait for your review.

After merge I will generate a gh-pages with the content generated by the test site, even though it isn't very good at least it will allow to see the "social sharing" shortcodes documentation. I will set as an issue to improve the styling of the page and make the minimal stuff to show it as a decent documentation site.

**Comment by ifraixedes** [comment]
@bhberson I'm done, please review it.

I've also published the gh-pages that I've generated of this branch, [take a look](http://ivan.fraixed.es/hugo-resources)

**Comment by mynamebrody** [comment]
I understand the reason to remove some of the `.IsNamedParamters` with Positional Params, but do we need to remove them all? Such as simple shortcodes where only one parameter is required, such as "twitter-follow" or "twitter-hashtag" ? So I could just pass:

```
  <!-- Twitter button with the only required parameter -->
  {{<twitter-hashtag hugo>}}
```

If we are moving towards simplicity, that would be easy to have both options, the simple one and then the more complex one? I'm also fixing some typos that I'll merge here in a second. But I can put some of the positional parameters back. I understand the need to not always have them, like the case of the "Pinterest-pinit" one.

**Comment by ifraixedes** [comment]
I did not realised after I finished and I wrote the docs and you have reviewed it about the shortcodes have only one required parameter. I don't see that they will be simpler to use with the option of the positional parameter, just a bit more comfortable with the tradeoff to replicate the code for the 2 options, even though it isn't a big deal. 

I've taken a look to read the shortcodes with the default parameter as first and only positional parameter and I can read them and understand the meaning of the parameter as the examples you mentioned. 
The only one that **I cannot see very clear the positional parameter is "twitter-share"** and for me the **"pinterest-pinit" is understandable if we apply the default parameter as positional parameter** because it's the URL of the image to pin.

So **I'm happy to add back the positional parameter option** only for the unique required parameter that they have, so **go ahead**.

On the other hand, I appreciate that you have gathered my typos and fixed my wrong English grammar, I'm not English native and I worked a bit late in the night so it didn't help :smiley: sorry about those.

I also pushed a commit now to fix the docs of "pinterest-pinit" I've realised it was wrong.

**Comment by ifraixedes** [comment]
Another thing about the `.gitignore` changes, just for curiosity.

I've always had to set `.DS_Store` to ignore all those files that OSX generated, for me it excluded them of any directory inside of the repo.

Because you created the "folders section" then you can move `.tmp` there, because that folder is generated by hugo server when it is ran by makefile `dev` and `dev-prod` targets.

Bear in mind that my last commit fixed them to be consistent to use `.tmp` as output; because I develop inside vagrant I always had `.tmp` directory and if you are using OSX then you had `dev` directory, which wasn't my intention.

**Comment by ifraixedes** [comment]
@bhberson please let me know if you can make the last bits & bobs to finish this PR and be able to merge otherwise I will try to do them the following days.

Thanks

**Comment by ifraixedes** [comment]
@bhberson I've done the changes to provide the short option to use the social sharing shortcodes through a positional parameter.

At the end due the [hugo documentation](http://gohugo.io/extras/shortcodes/#creating-your-own-shortcodes:10ef41a6c37b90d6a6452868d5ba00ba) and to have a consistent convention I've added that short option to twitter-share too, as it also requires only an unique parameter as the rest of them.

I would appreciate that you review it to be able to merge and close this PR.
Thanks.

**Comment by ifraixedes** [comment]
I've merged this to avoid delaying it more.

**Pull request merged**
